package com.twofactor.model;
// Generated Sep 30, 2017 6:26:51 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ScratchCode generated by hbm2java
 */
@Entity
@Table(name = "scratch_code", schema = "public")
public class ScratchCode implements java.io.Serializable {

	private long id;
	private User user;
	private int code;
	private boolean used;

	public ScratchCode() {
	}

	public ScratchCode(long id, User user, int code, boolean used) {
		this.id = id;
		this.user = user;
		this.code = code;
		this.used = used;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "code", nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@Column(name = "used", nullable = false)
	public boolean isUsed() {
		return this.used;
	}

	public void setUsed(boolean used) {
		this.used = used;
	}

}
