package com.twofactor.model;
// Generated Sep 14, 2017 6:01:48 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "public")
public class User implements java.io.Serializable {

	private String id;
	private String seed;

	public User() {
	}

	public User(String id) {
		this.id = id;
	}

	public User(String id, String seed) {
		this.id = id;
		this.seed = seed;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "seed")
	public String getSeed() {
		return this.seed;
	}

	public void setSeed(String seed) {
		this.seed = seed;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", seed=" + seed + "]";
	}
	
	

}
