package com.twofactor.model;
// Generated Sep 30, 2017 6:26:51 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "public")
public class User implements java.io.Serializable {

	private String id;
	private String seed;
	private Set<ScratchCode> scratchCodes = new HashSet<ScratchCode>(0);

	public User() {
	}

	public User(String id,String seed) {
		this.id = id;
		this.seed=seed;
	}

	public User(String id, String seed, Set<ScratchCode> scratchCodes) {
		this.id = id;
		this.seed = seed;
		this.scratchCodes = scratchCodes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "seed")
	public String getSeed() {
		return this.seed;
	}

	public void setSeed(String seed) {
		this.seed = seed;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ScratchCode> getScratchCodes() {
		return this.scratchCodes;
	}

	public void setScratchCodes(Set<ScratchCode> scratchCodes) {
		this.scratchCodes = scratchCodes;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", seed=" + seed + "]";
	}
	
	

}
